### PR TITLE
User and Item Tracking and Saving in DB

### PR DESCRIPTION
**Pull request by ansaries**
Added following functionalities:

1. I added userId and itemNumber passthrough fields, so that we may get the same in the notification process.
2. I added handlePayment() sample method, for developers to understand how they may save the payments/transactions information.

please have a look and let me know if you may have any comments.

p.s: I have created the same using angularjs component button instead of your blaze code. Can you help me in publishing the same as I have never published a package in Atomosphere yet.

### CODE REVIEW

**Comment by ie76** [comment]
Thank you @ansaries you have done some improvement to the paypal button, i will pull your branch and i will test. For the first sight, i can change some featured you made, to make it more "Meteor" like calling some methods not functions. 

If you want to publish a meteor package, it's **Super Easy**. Create a atmosphere account and then run in your terminal "meteor create --package yourUsernma:package-name" and here you are. Once you edit it. Publish it with "meteor publish --create". I can help you sure, just send me your meteor package repo. 

Thanks for your time.

**Comment by ie76** [comment]
Hello @ansaries i have made some changes to the repo. Thanks for your time again.

**Comment by ansaries** [comment]
hey,
@ie76 I did not get the userId from `this.userId` in server method as the request came from a different domain. Are you sure you are getting the userId in your Meteor.method?

**Comment by ie76** [comment]
@ansaries thank you, i didn't notice that. I just patched the issue, please can you check again !

**Pull request merged**
